# Generated by Django 2.2.10 on 2021-01-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pool name', max_length=256)),
                ('start_date', models.DateTimeField(editable=False, help_text='Pool start date')),
                ('end_date', models.DateTimeField(help_text='Pool end date')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('text', 'Text answer'), ('radio', 'One answer'), ('checkbox', 'Multiple answer')], help_text='(text, radio, checkbox)', max_length=8)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Pool')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='Suggested answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='User ID')),
                ('text_answer', models.TextField(blank=True, default='(leave empty if radio or checkbox question)', help_text='Text answer')),
                ('chosen_answers', models.ManyToManyField(blank=True, help_text='Set of answers for question with suggested answers (leave empty if text question)', to='pools.SuggestedAnswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Question')),
            ],
        ),
    ]
